image: node:8.4

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
    - mongo:3.2

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

variables:
    DOCKER_DRIVER: overlay
    DEPLOY_SERVER: maxfacts.york.ac.uk

stages:
    - test
    - deploy

build_and_test:
    stage: test
    script:
        # Needed for mongorestore
        - 'which mongorestore || ( apt-get -qq update -y; apt-get -qq install -y mongodb )'
        # Stop env file missing error
        - cp .env.example .env
        - mongorestore -h mongo -d maxfacts data/dump/maxfacts
        - yarn install
        - node_modules/.bin/gulp
        - npm run test:integrations

deploy:
    stage: deploy
    only:
        - schedules
    script:
        # Install ssh-agent if not already installed, it is required by Docker.
        # (change apt-get to yum if you use a CentOS-based image)
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
          # Run ssh-agent (inside the build environment)
        - eval $(ssh-agent -s)
          # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
        - ssh-add <(echo "$SSH_PRIVATE_KEY")
        - ssh $DEPLOY_SERVER 'cd Maxfacts && git pull && npm run deploy'
