# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
    - mongo:3.2

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
    paths:
        - node_modules/

# Install mongo restore
before_script:
    - apt-get -qq update -y; apt-get -qq install -y mongodb

variables:
    DOCKER_DRIVER: overlay

test_async:
    script:
        # Stop env file missing error
        - echo "MONGO_URI=mongo/maxfacts" > .env
        - echo "OAUTH_CALLBACK=http://localhost:3000/auth/callback" >> .env
        - cd backups/$(command ls -t backups | head -1)
        - sleep 10 # Wait for Mongo service to start 
        - mongorestore -h mongo -d maxfacts maxfacts
        - npm install --silent
        - npm run test:integrations
