# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
    - mongo:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
# cache:
#    paths:
#        - node_modules/

# Install mongo restore
before_script:
    - apt-get -qq update -y; apt-get -qq install -y mongodb

variables:
    DOCKER_DRIVER: overlay

web_server:
    script:
        # Stop env file missing error
        - cp .env.example .env
        - npm install -g yarn gulp
        - yarn install
        - cd backups/$(command ls -t backups | head -1)
        - for i in 1 2 3 4 5 6 7 8 9 10; do mongorestore -h mongo -d maxfacts maxfacts && break || sleep 2; done
        - cd ../..
        - gulp clean && gulp
        - npm run test:integrations
