version: '2'
services:
    app:
        image: laurenkt/maxfacts:latest
        volumes:
            - ./data/storage:/opt/lt696dev/content
            - ./build:/home/node/app
            - /home/node/app/node_modules # use node_modules local to the image to avoid platform conflicts
        links:
            - mongo
    mongo:
        image: mongo:3.2
        volumes:
            - ./data/db:/data/db
        ports:
            - '27017:27017'
        command: mongod --logpath=/dev/null # --smallfiles --fork --quiet
    restore:
        build:
            context: .
            dockerfile: mongo.Dockerfile
        volumes:
            - ./data/dump:/data/dump
        links:
            - mongo
    nginx:
        #TODO: logs
        image: nginx:1.13-alpine
        ports:
            - '8080:80'
        links:
            - app
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
