version: '2'
services:
    app:
        build: .
        ports:
            - '3000:3000'
        links:
            - mongo
    mongo:
        image: mongo:3.2
        volumes:
            - ./data/db:/data/db
        ports:
            - '27017:27017'
        command: mongod --logpath=/dev/null # --smallfiles --fork --quiet
    nginx:
        #TODO: logs
        image: nginx:1.13-alpine
        ports:
            - '80:80'
        links:
            - app
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
