version: '2'
volumes:
    node_modules:
services:
    app:
        image: laurenkt/maxfacts:latest
        volumes:
            - ./data/storage:/opt/lt696dev/content:delegated
            #- .:/home/node/app:delegated
            - ./data/dump:/home/node/app/data/dump:delegated
            #- node_modules:/home/node/app_node_modules
            #- /home/node/app/node_modules # use node_modules local to the image to avoid platform conflicts
        links:
            - mongo
    mongo:
        image: mongo:5
        volumes:
            - ./data/db:/data/db
        ports:
            - '27017:27017'
        command: mongod --logpath=/dev/null # --smallfiles --fork --quiet
    restore:
        build:
            context: .
            dockerfile: mongo.Dockerfile
        volumes:
            - ./data/dump:/data/dump:delegated
        links:
            - mongo
    nginx:
        #TODO: logs
        image: nginx:1.13-alpine
        ports:
            - '8080:80'
        links:
            - app
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:delegated
